"""init

Revision ID: 7d461942a7a2
Revises: 
Create Date: 2025-03-04 13:08:07.336728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d461942a7a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdn',
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('redirect_each_n_requests', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('host')
    )
    op.create_index(op.f('ix_cdn_host'), 'cdn', ['host'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cdn_host'), table_name='cdn')
    op.drop_table('cdn')
    # ### end Alembic commands ###
